// The coming-soon page's copy in de, en and fa, one table per language (CONTENT-TODO CR-1080..CR-1085: all of it is placeholder until the final content review).
// scripts/soon-pages.mjs renders soon/index.html once per language from these tables, so /, /en/ and /fa/ are separate, crawlable pages.

export const T = {
  de:{dir:"ltr",
    // BR-09 (CONTENT-TODO CR-1103, CR-1104): the chips under the role and the three learning snippets.
    chip1:"Systemintegration",
    chip2:"Netzwerke · Linux",
    chip3:"Trier, Deutschland",
    tipLabel:"Wussten Sie schon?",
    tip1:"Für einen Computer ist der Buchstabe A die Zahl 65 – gespeichert als acht Bits, also achtmal an oder aus.",
    tip2:"Der Befehl ping misst, wie lange ein kleines Datenpaket zu einem anderen Rechner und wieder zurück braucht.",
    tip3:"Dieser Adressbereich ist privat und für lokale Netze reserviert. Die 16 nach dem Schrägstrich heißt: Die ersten 16 Bits benennen das Netz, die übrigen 16 reichen für 65.536 Adressen.",
    title:"Ahmadreza Taheri – Fachinformatiker (Ausbildung), Trier",
    language:"Sprache", status:"Amonel · v1.0 im Aufbau",
    role:"Fachinformatiker für Systemintegration in Ausbildung · Trier",
    background:"Mit Hintergrund in Computer- und Handyreparatur",
    intro:"Hier entsteht mein persönliches Portfolio. Noch ist es nicht fertig – auf dieser Seite sehen Sie, was kommt und wie weit ich schon bin.",
    write:"E-Mail schreiben",
    whatTitle:"Was hier entsteht",
    whatLead:"Eine Reise durch rund 80 Jahre Computergeschichte, die sich am Ende in mein eigenes Betriebssystem im Browser verwandelt: Amonel OS.",
    c1t:"Durch die Geschichte scrollen", c1:"Sieben Epochen, von ENIAC 1946 bis zur Cloud von heute. Jede zeigt etwas über Computer, das bis heute gilt.",
    c2t:"Kleine Rätsel", c2:"In jeder Epoche wartet ein Rätsel. Sie lösen es selbst – oder sehen zu, wie es sich von allein löst.",
    c3t:"Amonel OS", c3:"Am Ende der Reise öffnet sich ein Desktop im Browser, mit Apps, die wirklich funktionieren: Terminal, Netzwerk-Werkzeuge, Quiz und mehr.",
    c4t:"Mein Weg", c4:"Von Teheran nach Trier: Werdegang, Lebenslauf und Kontakt. Alles auf Deutsch, Englisch und Persisch.",
    progressTitle:"So weit bin ich", overall:"der Arbeit sind erledigt",
    note:"Gewichtet nach Aufwand: Große Aufgaben zählen mehr als kleine.",
    journey:"Reise durch die Computergeschichte", journeyText:"Sieben Epochen zum Durchscrollen, mit Bildern, Übergängen und Texten.",
    desktop:"Amonel OS: Desktop und Apps", desktopText:"Das Betriebssystem im Browser: Fenster, Taskleiste und die Apps darin.",
    puzzles:"Rätsel und Spiele", puzzlesText:"Die sieben Rätsel, das Computer-Quiz und kleine Spiele wie Snake.",
    about:"Über mich, Lebenslauf und Kontakt", aboutText:"Werdegang, Foto, Lebenslauf, Kontakt und meine Profile.",
    legal:"Recht und Datenschutz", legalText:"Impressum, Datenschutz und die rechtliche Prüfung jeder Funktion.",
    seo:"Suchmaschinen, Tempo und Barrierefreiheit", seoText:"Schnell laden, gut gefunden werden und für alle bedienbar sein – auch auf dem Handy.",
    launch:"Letzte Texte, Logo und Start", launchText:"Alle Texte gemeinsam prüfen, das endgültige Logo, dann der Start.",
    counts:"{d} fertig · {p} in Arbeit · {m} offen", stamp:"Stand:",
    nextTitle:"Wie es weitergeht",
    next:"Als Nächstes: die letzten Apps, Tests auf echten Handys und Tablets, Foto und Lebenslauf. Danach gehe ich jeden Text noch einmal durch – dann geht die Seite online.",
    contact:"Sie möchten mich schon jetzt erreichen? Schreiben Sie mir gern:",
    imprint:"Impressum", privacy:"Datenschutz", legalNav:"Rechtliches", prefix:""},
  en:{dir:"ltr",
    // BR-09 (CONTENT-TODO CR-1103, CR-1104): the chips under the role and the three learning snippets.
    chip1:"System integration",
    chip2:"Networks · Linux",
    chip3:"Trier, Germany",
    tipLabel:"Did you know?",
    tip1:"To a computer, the letter A is the number 65 – stored as eight bits, eight times on or off.",
    tip2:"The ping command measures how long a small data packet takes to reach another computer and come back.",
    tip3:"This address range is private, reserved for local networks. The 16 after the slash means: the first 16 bits name the network, and the other 16 are enough for 65,536 addresses.",
    title:"Ahmadreza Taheri – IT System Integration Apprentice, Trier",
    language:"Language", status:"Amonel · v1.0 in progress",
    role:"IT specialist for system integration in training · Trier",
    background:"With a background in computer and mobile phone repair",
    intro:"This is where my personal portfolio is being built. It isn't finished yet – this page shows what is coming and how far along it is.",
    write:"Send an email",
    whatTitle:"What is being built",
    whatLead:"A journey through about 80 years of computer history that turns into my own operating system in the browser: Amonel OS.",
    c1t:"Scroll through history", c1:"Seven eras, from ENIAC in 1946 to today's cloud. Each one shows something about computers that is still true today.",
    c2t:"Small puzzles", c2:"Every era has a puzzle waiting. Solve it yourself – or watch it solve itself.",
    c3t:"Amonel OS", c3:"At the end of the journey a desktop opens in your browser, with apps that really work: a terminal, network tools, a quiz and more.",
    c4t:"My path", c4:"From Tehran to Trier: my background, CV and contact. All in German, English and Persian.",
    progressTitle:"How far along it is", overall:"of the work is done",
    note:"Weighted by effort: big tasks count more than small ones.",
    journey:"Journey through computer history", journeyText:"Seven eras to scroll through, with pictures, transitions and texts.",
    desktop:"Amonel OS: desktop and apps", desktopText:"The operating system in the browser: windows, a taskbar and the apps inside.",
    puzzles:"Puzzles and games", puzzlesText:"The seven puzzles, the computer quiz and small games such as Snake.",
    about:"About me, CV and contact", aboutText:"My background, photo, CV, contact and profiles.",
    legal:"Legal and privacy", legalText:"Imprint, privacy policy and a legal check of every feature.",
    seo:"Search engines, speed and accessibility", seoText:"Loading fast, being easy to find and usable by everyone – on phones too.",
    launch:"Final texts, logo and launch", launchText:"Reviewing every text together, the final logo, then the launch.",
    counts:"{d} done · {p} in progress · {m} to do", stamp:"Last updated:",
    nextTitle:"What's next",
    next:"Next up: the last apps, tests on real phones and tablets, a photo and my CV. Then I'll go through every text once more – and the site goes live.",
    contact:"Would you like to get in touch already? I'd be glad to hear from you:",
    imprint:"Imprint", privacy:"Privacy", legalNav:"Legal", prefix:"/en"},
  fa:{dir:"rtl",
    // BR-09 (CONTENT-TODO CR-1103, CR-1104): the chips under the role and the three learning snippets.
    chip1:"یکپارچه‌سازی سیستم‌ها",
    chip2:"شبکه · Linux",
    chip3:"تریر، آلمان",
    tipLabel:"می‌دانستید؟",
    tip1:"برای رایانه، حرف A همان عدد ۶۵ است که به شکل هشت بیت ذخیره می‌شود: هشت بار روشن یا خاموش.",
    tip2:"فرمان ping می‌سنجد که یک بستهٔ کوچک داده چقدر طول می‌کشد تا به رایانهٔ دیگری برسد و برگردد.",
    tip3:"این محدودهٔ نشانی خصوصی است و برای شبکه‌های محلی کنار گذاشته شده. عدد ۱۶ بعد از خط مورب یعنی ۱۶ بیت اول نشانگر شبکه است و ۱۶ بیت باقی‌مانده برای ۶۵٬۵۳۶ نشانی کافی است.",
    title:"احمدرضا طاهری – کارآموز فناوری اطلاعات، تریر",
    language:"زبان", status:"Amonel · نسخهٔ ۱٫۰ در حال ساخت",
    role:"کارآموز متخصص فناوری اطلاعات (یکپارچه‌سازی سیستم‌ها) · تریر",
    background:"با پیشینهٔ تعمیر کامپیوتر و موبایل",
    intro:"اینجا نمونه‌کار شخصی من ساخته می‌شود. هنوز کامل نیست؛ در این صفحه می‌بینید چه چیزی در راه است و کار تا کجا پیش رفته است.",
    write:"ایمیل بفرستید",
    whatTitle:"چه چیزی ساخته می‌شود",
    whatLead:"سفری در حدود ۸۰ سال تاریخ رایانه که در پایان به سیستم‌عامل خود من در مرورگر تبدیل می‌شود: Amonel OS.",
    c1t:"سفر در تاریخ", c1:"هفت دوره، از ENIAC در سال ۱۹۴۶ تا ابر امروز. هر دوره نکته‌ای دربارهٔ رایانه‌ها نشان می‌دهد که هنوز هم درست است.",
    c2t:"معماهای کوچک", c2:"در هر دوره یک معما منتظر شماست. می‌توانید خودتان حلش کنید یا تماشا کنید که چطور خودش حل می‌شود.",
    c3t:"Amonel OS", c3:"در پایان سفر، یک میزکار در مرورگر شما باز می‌شود با برنامه‌هایی که واقعاً کار می‌کنند: ترمینال، ابزارهای شبکه، مسابقه و چیزهای دیگر.",
    c4t:"مسیر من", c4:"از تهران تا تریر: سوابق، رزومه و راه تماس. همه به آلمانی، انگلیسی و فارسی.",
    progressTitle:"کار تا کجا پیش رفته است", overall:"از کل کار انجام شده است",
    note:"بر اساس حجم کار: کارهای بزرگ بیشتر از کارهای کوچک حساب می‌شوند.",
    journey:"سفر در تاریخ رایانه", journeyText:"هفت دوره برای پیمایش، با تصویر، گذار و متن.",
    desktop:"میزکار و برنامه‌های Amonel OS", desktopText:"سیستم‌عامل درون مرورگر: پنجره‌ها، نوار وظیفه و برنامه‌های آن.",
    puzzles:"معماها و بازی‌ها", puzzlesText:"هفت معما، مسابقهٔ رایانه و بازی‌های کوچکی مثل Snake.",
    about:"دربارهٔ من، رزومه و تماس", aboutText:"سوابق، عکس، رزومه، راه تماس و پروفایل‌های من.",
    legal:"مسائل حقوقی و حریم خصوصی", legalText:"اطلاعات ناشر، حریم خصوصی و بررسی حقوقی هر بخش.",
    seo:"موتورهای جست‌وجو، سرعت و دسترس‌پذیری", seoText:"سریع بارگیری شود، به‌آسانی پیدا شود و برای همه قابل استفاده باشد؛ روی گوشی هم.",
    launch:"متن‌های نهایی، لوگو و انتشار", launchText:"بازبینی مشترک همهٔ متن‌ها، لوگوی نهایی و سپس انتشار.",
    counts:"{d} انجام شده · {p} در حال انجام · {m} باقی‌مانده", stamp:"آخرین به‌روزرسانی:",
    nextTitle:"قدم بعدی",
    next:"در ادامه: آخرین برنامه‌ها، آزمایش روی گوشی و تبلت واقعی، عکس و رزومه. بعد همهٔ متن‌ها را یک بار دیگر بازبینی می‌کنم و سایت منتشر می‌شود.",
    contact:"می‌خواهید همین حالا با من در تماس باشید؟ خوشحال می‌شوم برایم بنویسید:",
    imprint:"اطلاعات ناشر", privacy:"حریم خصوصی", legalNav:"اطلاعات حقوقی", prefix:"/fa"}
};

// One line per language under the role, so every visitor sees the name in their own script.
export const ALT = {
  de: '<p lang="de" dir="ltr">Fachinformatiker für Systemintegration in Ausbildung, Trier – mein Portfolio entsteht gerade.</p>',
  en: '<p lang="en" dir="ltr">IT specialist for system integration in training, Trier – my portfolio is coming soon.</p>',
  fa: '<p lang="fa" dir="rtl">احمدرضا طاهری، کارآموز متخصص فناوری اطلاعات در تریر – نمونه‌کار من به‌زودی منتشر می‌شود.</p>',
};
// In Persian the Latin h1 gets the name in Persian script right under it.
export const FA_NAME = '<p class="fa-name" lang="fa" dir="rtl">احمدرضا طاهری</p>';

// Search-result and share texts per language (CONTENT-TODO CR-1084, CR-1085).
export const SEO = {
  de: {
    description: 'Ahmadreza Taheri, Fachinformatiker für Systemintegration in Ausbildung in Trier, mit Hintergrund in Computer- und Handyreparatur. Portfolio Amonel.',
    shareDescription: 'Das Portfolio Amonel entsteht gerade: 80 Jahre Computergeschichte, die zu einem eigenen Betriebssystem im Browser werden.',
    imageAlt: 'Ahmadreza Taheri, Fachinformatiker für Systemintegration in Ausbildung, Trier – Portfolio Amonel',
  },
  en: {
    description: 'Ahmadreza Taheri, IT specialist for system integration in training in Trier, with a background in computer and mobile phone repair. Portfolio Amonel.',
    shareDescription: 'The portfolio Amonel is being built: 80 years of computer history that turn into an operating system of its own in the browser.',
    imageAlt: 'Ahmadreza Taheri, IT specialist for system integration in training, Trier – portfolio Amonel',
  },
  fa: {
    description: 'احمدرضا طاهری، کارآموز متخصص فناوری اطلاعات (یکپارچه‌سازی سیستم‌ها) در تریر، با پیشینهٔ تعمیر کامپیوتر و موبایل. نمونه‌کار Amonel: ۸۰ سال تاریخ رایانه.',
    shareDescription: 'نمونه‌کار Amonel در حال ساخت است: ۸۰ سال تاریخ رایانه که در مرورگر به یک سیستم‌عامل تبدیل می‌شود.',
    imageAlt: 'احمدرضا طاهری، کارآموز متخصص فناوری اطلاعات، تریر – نمونه‌کار Amonel',
  },
};
